package com.mts.account.config

object TickerData {
    fun getUsTickers(): List<String> {
        return part0() + part1() + part2() + part3() + part4() + 
               part5() + part6() + part7() + part8() + part9()
    }

    private fun part0() = listOf("SNEX", "GIS", "HR", "MSA", "PG", "HPQ", "ABT", "MOH", "ZM", "BR", "DLR", "CFR", "FITBI", "TRMB", "FHN", "WES", "ONBPP", "C", "WTS", "ATO", "MKSI", "TPGXL", "MTSI", "RL", "FNF", "INCY", "CSGP", "DTM", "NTRA", "MASI", "RPM", "CELC", "SIRI", "GPN", "THG", "P", "TME", "AGX", "SNDK", "ALB", "NEE", "MSCI", "RIOT", "AON", "ULS", "LLYVA", "RCL", "MDLZ", "AHR", "CEG", "CHD", "LAD", "INTC", "MSI", "TSN", "MAS", "OKLO", "ORI", "D", "ONTO", "VLYPO", "VMC", "MDGL", "ES", "BIIB", "MYRG", "RJF", "XOM", "PCAR", "GOOGL", "PM", "JBL", "LNT", "HBANM", "TTMI", "PCOR", "HLI", "VAL", "SCCO", "BRKR", "SNAP", "DLTR", "GM", "TKR", "SRE", "IT", "SATA", "WEC", "NBIX", "CAT", "CGNX", "SOMN", "AFRM", "AAOI", "PLTR", "LKQ", "FOX", "EVR", "PRU", "AMG")
    private fun part1() = listOf("TXRH", "ALNY", "AROC", "AN", "VICR", "MORN", "SYRE", "SWKS", "HSY", "WPC", "VIRT", "ETR", "PFG", "NFLX", "STRL", "MTCH", "VG", "PL", "XEL", "COHR", "INVH", "MKL", "BBY", "KEYS", "RRX", "HBAN", "CRUS", "RVTY", "POOL", "THC", "BOKF", "W", "VOYA", "AGNCM", "HAS", "R", "CTAS", "T", "DOV", "SARO", "OSCR", "VFC", "CBC", "CRCL", "SPXC", "FSLR", "WSM", "HUBB", "STLD", "AMH", "SFD", "PB", "SOFI", "TPG", "BMNR", "EFX", "TRV", "FITB", "HRL", "WTFC", "SMMT", "RKLB", "CDW", "VEEV", "CLF", "DT", "FISV", "NE", "UTHR", "LOW", "MIRM", "SOJE", "NXT", "HPE", "SWK", "CNM", "BLD", "CMCSA", "DKNG", "CHDN", "VICI", "MTZ", "ELV", "COP", "AXON", "PKG", "GBCI", "REXR", "AVT", "EIX", "ET", "ABBV", "AGNCO", "ITT", "DKS", "SANM", "COKE", "QCOM", "OXY", "FTAI")
    private fun part2() = listOf("UGI", "NSC", "AMT", "RF", "CE", "MPWR", "CGON", "CRM", "BAX", "STRC", "IMVT", "EWBC", "LLYVK", "NDAQ", "PEN", "KRMN", "APOS", "AA", "QBTS", "ROKU", "HCA", "IFF", "USB", "UNH", "MIDD", "FCX", "HII", "DIS", "ATR", "OKTA", "AMZN", "AUGO", "VIAV", "ILMN", "DPZ", "RSG", "GME", "GGG", "OHI", "V", "ERIE", "FAF", "ESS", "SLMBP", "CSX", "SPG", "MSFT", "CPAY", "JNJ", "FANG", "GLW", "NTAP", "STRF", "AEE", "MSTR", "WLK", "IDXX", "NYT", "PRMB", "MDLN", "ZION", "ALLE", "ZG", "EVRG", "GEHC", "ACI", "AJG", "QXO", "APGE", "ARMK", "AIG", "GWW", "MU", "FCNCA", "EBAY", "IBKR", "PTC", "FIX", "IRM", "BRO", "CQP", "GDDY", "KMB", "VLTO", "CAH", "CHRD", "ED", "FWONA", "TRNO", "JKHY", "KIM", "AEP", "SUI", "CRBG", "CMS", "PRS", "BRK-B", "URI", "NI", "YUMC")
    private fun part3() = listOf("AMAT", "VLYPP", "STZ", "KDP", "FITBP", "KRYS", "KHC", "AM", "WRB", "DE", "H", "REG", "SSNC", "WTRG", "TXN", "CWAN", "AIZ", "FROG", "EPD", "TW", "LH", "BIO", "PRI", "MNST", "TRU", "A", "EHC", "DGX", "LTH", "RBLX", "GD", "FTNT", "DDS", "ZS", "CHYM", "BYD", "DG", "DY", "STT", "KVUE", "BG", "REGN", "MLM", "VIK", "IVZ", "TOL", "CNC", "TMO", "BTSG", "ECG", "TXNM", "PSKY", "CR", "LNG", "HEI", "HON", "SFM", "GAP", "TMUS", "MEDP", "INGR", "JBHT", "VRSN", "NOW", "RS", "FLS", "TECH", "DRI", "RYTM", "MP", "PPLC", "NOV", "MPLX", "FLY", "HD", "WFRD", "PLXS", "MAR", "MA", "FR", "CGABL", "PWR", "MDT", "WWD", "ACA", "ADBE", "XYL", "WFC", "HLT", "ASTS", "CPRT", "GJS", "YUM", "ABNB", "KLAC", "LII", "CRWD", "PPL", "CLH", "AXTA")
    private fun part4() = listOf("MXL", "TDY", "EQR", "NUE", "MHK", "KMI", "SYM", "TOST", "TTEK", "SMCI", "SBAC", "PH", "IDA", "EMR", "DD", "ADM", "TRGP", "NOC", "SOLS", "ONBPO", "PFH", "EXPE", "BROS", "AVY", "IBRX", "TLN", "FTV", "GTLS", "KKRS", "NIO", "FTS", "F", "MOS", "GH", "ESI", "GNRC", "AMP", "LITE", "CORZ", "BA", "CTSH", "TWLO", "WMG", "OC", "SNX", "DOCN", "CMSD", "PAYC", "DASH", "FRVO", "CPNG", "TPL", "HXL", "DOW", "VLYPN", "BDX", "SEIC", "ODFL", "BRX", "JBTM", "NLY", "CSCO", "PAA", "LMT", "HUM", "CHTR", "NKE", "FIG", "HBANZ", "CRDO", "RYN", "MMM", "MDB", "TSCO", "NET", "KTOS", "CAVA", "GKOS", "CIFR", "EMP", "CCL", "PLD", "PPC", "WST", "BJ", "JPM", "LUV", "EAT", "YOU", "ATI", "ARW", "CG", "ARES", "UAL", "ECL", "HST", "FICO", "USFD", "MS", "FIS")
    private fun part5() = listOf("CMSA", "AXSM", "MKC", "BKNG", "MTB", "LLY", "ARWR", "SNPS", "CRS", "SYF", "PRH", "LVS", "AGNCP", "AQNB", "TFC", "MCHP", "APG", "GEV", "AVB", "EQIX", "RYAN", "MSGS", "VSNT", "FWONK", "EXR", "WBD", "IBP", "AKAM", "PSX", "LEA", "JXN", "UDR", "OGE", "ELAN", "PGR", "PTGX", "PNW", "IR", "RBRK", "IDCC", "CASY", "MRK", "MCK", "SITM", "APO", "BEPC", "GE", "CI", "AR", "LNTH", "GPC", "ULTA", "STE", "CUBE", "CMG", "ICE", "DTE", "TTC", "RTX", "SATS", "NTNX", "PJT", "IBM", "ORA", "ONB", "DBX", "JLL", "OKE", "EL", "COIN", "CCI", "DHI", "STWD", "ALGM", "CME", "DUK", "SWX", "PNC", "VRTX", "TRI", "FNB", "META", "NNN", "HBANP", "BALL", "FRT", "IONS", "HIG", "STRK", "MTDR", "TYL", "AGNCL", "GSAT", "CET", "PR", "FIVE", "MLI", "APH", "DHR", "CSL")
    private fun part6() = listOf("KEX", "BRK-A", "MRVL", "NEU", "VTRS", "Q", "WM", "OSK", "FDS", "DAL", "DVA", "LHX", "EME", "MANH", "AUR", "GEN", "ARE", "TGTX", "ISRG", "GS", "SMTC", "ARCC", "LUNR", "RGA", "WMB", "PPG", "EA", "AES", "APA", "BXP", "TDG", "UBER", "BEN", "CELH", "Z", "CART", "LSCC", "CHRW", "AOS", "XE", "MCD", "PAYX", "CLX", "SN", "SGI", "TEM", "SE", "SYY", "GWRE", "CVNA", "RIVN", "NWSA", "FSS", "TKO", "OMC", "INGM", "AWK", "GOOG", "STAG", "EOG", "BMRN", "SSD", "ALL", "DUKB", "ENSG", "DCI", "ITW", "ADSK", "CENX", "AMD", "PFGC", "AIT", "ADI", "CPB", "LOGI", "LEN", "SCHW", "VTR", "AWI", "JOBY", "APD", "AVAV", "CIEN", "GATX", "AAL", "PINS", "RAL", "MCHPP", "SO", "RMD", "FITBM", "AMGN", "SYK", "U", "LFUS", "KNX", "PEP", "RBC", "KEY", "PRAX")
    private fun part7() = listOf("IQV", "L", "SF", "RGTI", "MO", "BKR", "EXE", "MUSA", "WAB", "SNA", "SREA", "BWA", "BE", "UMBF", "CTVA", "HUBS", "CACI", "PEG", "VST", "NWS", "ALSN", "RDDT", "SM", "GILD", "SAIL", "ANET", "SAIA", "PODD", "DELL", "TSLA", "CORT", "DAR", "ROK", "PNFP", "APLD", "COST", "AGNCN", "HSIC", "HBANL", "TTWO", "BK", "VRSK", "IOT", "ENTG", "LEVI", "EQPT", "CCK", "CMC", "ROP", "VSAT", "O", "LUMN", "CAG", "ADC", "ESE", "SOJD", "SOLV", "ZBH", "CORZZ", "DDOG", "MAA", "CF", "ALGN", "KKR", "FDX", "IEX", "APP", "BURL", "UHAL", "PFE", "KGS", "PCVX", "ON", "PANW", "EW", "WAT", "CW", "AGCO", "ORCL", "WCC", "RPRX", "HL", "NVDA", "LDOS", "OWL", "VLO", "AYI", "TPR", "HALO", "GVA", "ROAD", "ENS", "VNO", "HAL", "DINO", "HWM", "WY", "ROST", "SSB", "VNOM")
    private fun part8() = listOf("EPRT", "FCFS", "WYNN", "AAPL", "CMSC", "MCO", "IONQ", "LNC", "LW", "EXP", "WULF", "CHWY", "KNSL", "BPOP", "STEP", "JEF", "CDNS", "CTRE", "NUVL", "WMT", "LECO", "XYZ", "TXT", "BWXT", "PACS", "CINF", "INSM", "BLK", "AEIS", "ENPH", "WMS", "COLB", "RSI", "HUT", "MRSH", "INTU", "AXP", "ENJ", "NEM", "AMKR", "IP", "ADP", "NCLH", "RHP", "SOJC", "DOC", "PHM", "DECK", "MGM", "GFS", "NVR", "SRRK", "EAI", "PCG", "MSM", "RKT", "BSX", "EXPD", "EQH", "XPO", "FITBO", "WBS", "CARR", "RVMD", "FORM", "IESC", "TER", "WDC", "UI", "LPLA", "ZTS", "WAL", "WH", "RTO", "COR", "VZ", "BAH", "LINE", "NFG", "NTRS", "SCI", "AME", "SUN", "SJM", "GL", "PYPL", "FE", "MRNA", "MPC", "BLTE", "CYTK", "NDSN", "CL", "KYMR", "EXEL", "UNP", "COO", "POWL", "OMF", "LYV")
    private fun part9() = listOf("PAG", "TGT", "NRG", "STRD", "HOOD", "FOXA", "BLDR", "AGNC", "RGLD", "FLR", "AXTI", "BMY", "VLY", "URBN", "CBSH", "TBB", "BTSGU", "DOCU", "MET", "AAON", "CCZ", "TJX", "UHS", "CRWV", "BBIO", "CNP", "TEX", "HQY", "GLXY", "ZBRA", "QRVO", "EQT", "ARXS", "WELL", "CFG", "BX", "MOD", "CDE", "RRC", "LIN", "EMN", "KR", "UNM", "AGNCZ", "CRL", "OTIS", "SPGI", "ROL", "CVS", "ACT", "WDAY", "MWH", "AZO", "SHW", "PRIM", "DVN", "PTCT", "GMED", "ORLY", "ZWS", "ACM", "AVGO", "SLAB", "KNTK", "CBRE", "J", "FFIV", "PSA", "DXCM", "NXST", "CPT", "CNA", "VMI", "AFL", "RMBS", "CVX", "ALLY", "WSO", "FAST", "BRKRP", "SBUX", "BAC", "KO", "TROW", "GLPI", "VRT", "LAMR", "NPO", "LGN", "AFG", "COF", "BSY", "UPS", "SNOW", "EXC", "ALAB", "TTD", "LRCX", "CMI", "ELS")
}
