spring:
  application:
    name: trading-server
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8001
  tomcat:
    threads:
      max: 500
      min-spare: 100
    accept-count: 5000
    max-connections: 20000

ledger:
  url: http://localhost:8000
