spring:
  application:
    name: account-server
  datasource:
    url: jdbc:postgresql://localhost:5432/mts_db
    username: mts_user
    password: mts_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
