server {
    listen       80;
    server_name  localhost;

    # 보안: 허용된 IP만 접속 가능하도록 설정
    allow 100.106.38.67;
    allow 100.76.191.74;
    
    deny all;               # 그 외 모든 IP 차단

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # SPA 라우팅 지원
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
